# Generated by Django 4.2.11 on 2024-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='class',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='class',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_en',
            field=models.CharField(max_length=1024, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_ru',
            field=models.CharField(max_length=1024, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='frontendtranslation',
            name='text_uz',
            field=models.CharField(max_length=1024, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='school',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='school',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='school',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
