# Generated by Django 4.2.11 on 2024-04-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_class_title_en_class_title_ru_class_title_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='class',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='class',
            name='title_uz',
        ),
    ]
