# Generated by Django 4.2.11 on 2024-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="bot_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bot token"
            ),
        ),
    ]
