# Generated by Django 4.2.11 on 2024-04-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schools",
                to="common.district",
            ),
        ),
    ]
