# Generated by Django 4.2.11 on 2024-05-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0016_alter_notification_class_room_and_more"),
        ("olimpic", "0021_alter_olimpic_class_room"),
        ("common", "0007_alter_school_district"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Class",
        ),
    ]
