# Generated by Django 5.0.9 on 2024-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Skill"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_qr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Skill"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Skill"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_uz",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Skill"
            ),
        ),
    ]
