# Generated by Django 5.0.9 on 2024-09-13 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=255)),
                ("message_id", models.PositiveIntegerField(blank=True, null=True)),
                ("message_text", models.TextField(blank=True, null=True)),
                ("last_update", models.DateField(default=django.utils.timezone.now)),
                ("message_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
