# Generated by Django 5.0.9 on 2024-09-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0002_reportmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(default="Notification", verbose_name="Message"),
                ),
            ],
            options={
                "verbose_name": "Daily Message",
                "verbose_name_plural": "Daily Messages",
            },
        ),
    ]
