# Generated by Django 5.0.9 on 2024-09-06 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0002_skill_title_en_skill_title_qr_skill_title_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="plan",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="User Plan"
            ),
        ),
        migrations.CreateModel(
            name="SelectPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_uz", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("title_qr", models.CharField(max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text_button", "Text Button"),
                            ("text_cv_link", "Text CV Link"),
                            ("text_link", "Text Link"),
                        ],
                        help_text="Type of action for this plan (button, CV link, or regular link).",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("content", models.TextField(null=True, verbose_name="Content")),
                ("content_uz", models.TextField(null=True, verbose_name="Content")),
                ("content_ru", models.TextField(null=True, verbose_name="Content")),
                ("content_en", models.TextField(null=True, verbose_name="Content")),
                ("content_qr", models.TextField(null=True, verbose_name="Content")),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Link"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent plan, if this is a sub-plan.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tgbot.selectplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanButtons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="Keyboard name"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Keyboard name"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Keyboard name"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Keyboard name"
                    ),
                ),
                (
                    "title_qr",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Keyboard name"
                    ),
                ),
                ("content", models.TextField(verbose_name="Content")),
                ("content_uz", models.TextField(null=True, verbose_name="Content")),
                ("content_ru", models.TextField(null=True, verbose_name="Content")),
                ("content_en", models.TextField(null=True, verbose_name="Content")),
                ("content_qr", models.TextField(null=True, verbose_name="Content")),
                ("link", models.URLField(blank=True, null=True, verbose_name="Link")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="tgbot.selectplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
