# Generated by Django 4.2.16 on 2024-10-20 04:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0003_dailymessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Group name")),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Group name"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Group name"
                    ),
                ),
                ("topic_id", models.CharField(max_length=255, verbose_name="Topic ID")),
                (
                    "chat_id",
                    models.CharField(
                        default="-1002237773868", max_length=255, verbose_name="Chat ID"
                    ),
                ),
                ("ordering", models.IntegerField(default=1, verbose_name="Ordering")),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "db_table": "groups",
            },
        ),
        migrations.CreateModel(
            name="LastTopicID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic_id", models.CharField(max_length=255, verbose_name="Topic ID")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="telegrambutton",
            name="text",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Button Text"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambutton",
            name="text_ru",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Button Text"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambutton",
            name="text_uz",
            field=ckeditor.fields.RichTextField(
                blank=True, null=True, verbose_name="Button Text"
            ),
        ),
        migrations.AddField(
            model_name="reportmessage",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tgbot.group",
                verbose_name="Group",
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tgbot.group",
                verbose_name="Group",
            ),
        ),
    ]
