# Generated by Django 4.2.16 on 2024-10-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0004_group_lasttopicid_alter_telegrambutton_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Blocked At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.telegramprofile",
                        verbose_name="Blocked User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked User",
                "verbose_name_plural": "Blocked Users",
            },
        ),
    ]
