# Generated by Django 5.0.9 on 2024-10-25 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0005_blockeduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_day", models.IntegerField()),
                ("book", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("pages_read", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.telegramprofile",
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
