# Generated by Django 4.2.16 on 2024-11-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0006_confirmationreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmationreport",
            name="book",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
