# Generated by Django 4.2.16 on 2024-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0007_confirmationreport_book_telegramprofile_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
