# Generated by Django 4.2.11 on 2024-04-16 07:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Olimpic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "title_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Title"),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Description"),
                ),
                (
                    "description_uz",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Description"
                    ),
                ),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Description"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="olimpics"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="Text")),
                (
                    "text_uz",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Text"),
                ),
                (
                    "text_ru",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Text"),
                ),
                (
                    "text_en",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Text"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Duration (seconds)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="questions"),
                ),
                (
                    "file_content",
                    models.FileField(blank=True, null=True, upload_to="questions"),
                ),
                (
                    "olimpic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="olimpic.olimpic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_uz", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="olimpic.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
