# Generated by Django 4.2.11 on 2024-04-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_telegramprofile__user_data"),
        ("olimpic", "0003_userquestionoption_delete_useranswer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOlimpic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("wrong_answers", models.PositiveIntegerField(default=0)),
                (
                    "olimpic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_olimpics",
                        to="olimpic.olimpic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_olimpics",
                        to="bot.telegramprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
