# Generated by Django 4.2.11 on 2024-04-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0004_userolimpic"),
    ]

    operations = [
        migrations.AddField(
            model_name="userolimpic",
            name="not_answered",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
