# Generated by Django 4.2.11 on 2024-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0005_userolimpic_not_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestion",
            name="next_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
