# Generated by Django 4.2.11 on 2024-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0006_userquestion_next_task_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userquestion",
            old_name="next_task_id",
            new_name="task_id",
        ),
        migrations.AddField(
            model_name="userquestion",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
    ]
