# Generated by Django 4.2.11 on 2024-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0007_rename_next_task_id_userquestion_task_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestion",
            name="next_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
