# Generated by Django 4.2.11 on 2024-04-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0008_userquestion_next_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestion",
            name="message_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
