# Generated by Django 4.2.11 on 2024-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0009_userquestion_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userolimpic",
            name="certificate",
            field=models.FileField(blank=True, null=True, upload_to="certificates"),
        ),
        migrations.AddField(
            model_name="userolimpic",
            name="olimpic_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
