# Generated by Django 4.2.11 on 2024-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0010_userolimpic_certificate_userolimpic_olimpic_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestion",
            name="content_message_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
