# Generated by Django 4.2.11 on 2024-04-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0012_alter_userolimpic_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userolimpic",
            name="correct_answers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userolimpic",
            name="not_answered",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userolimpic",
            name="wrong_answers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
