# Generated by Django 4.2.11 on 2024-04-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0013_alter_userolimpic_correct_answers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userolimpic",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
