# Generated by Django 4.2.11 on 2024-04-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0014_alter_userolimpic_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="OlimpicCertifeicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "certificate",
                    models.FileField(blank=True, null=True, upload_to="certificates"),
                ),
                (
                    "olimpic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="olimpic.olimpic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
