# Generated by Django 4.2.11 on 2024-04-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0015_olimpiccertifeicate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userolimpic",
            name="olimpic_time",
        ),
        migrations.AddField(
            model_name="userolimpic",
            name="olimpic_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
