# Generated by Django 4.2.11 on 2024-04-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_school_district"),
        ("olimpic", "0018_alter_olimpic_result_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="olimpic",
            name="class_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olimpic_class_rooms",
                to="common.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="olimpic",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olimpic_districts",
                to="common.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="olimpic",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olimpic_regions",
                to="common.region",
                verbose_name="Region",
            ),
        ),
        migrations.AddField(
            model_name="olimpic",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olimpic_schools",
                to="common.school",
                verbose_name="School",
            ),
        ),
    ]
