# Generated by Django 4.2.11 on 2024-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0019_olimpic_class_room_olimpic_district_olimpic_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="olimpic",
            name="is_all_users",
            field=models.BooleanField(default=False, verbose_name="Is All Users"),
        ),
    ]
