# Generated by Django 4.2.11 on 2024-05-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0020_olimpic_is_all_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="olimpic",
            name="class_room",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5-sinf", "5-sinf"),
                    ("6-sinf", "6-sinf"),
                    ("7-sinf", "7-sinf"),
                    ("8-sinf", "8-sinf"),
                    ("9-sinf", "9-sinf"),
                    ("10-sinf", "10-sinf"),
                    ("11-sinf", "11-sinf"),
                ],
                max_length=255,
                null=True,
                verbose_name="Class Room",
            ),
        ),
    ]
