# Generated by Django 4.2.11 on 2024-05-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0021_alter_olimpic_class_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="olimpic",
            name="certificate_generate",
            field=models.DateTimeField(null=True, verbose_name="Certificate Generate"),
        ),
    ]
