# Generated by Django 4.2.11 on 2024-05-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0022_olimpic_certificate_generate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="olimpiccertifeicate",
            name="certificate",
            field=models.ImageField(blank=True, null=True, upload_to="certificates"),
        ),
    ]
