# Generated by Django 4.2.11 on 2024-05-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpic', '0023_alter_olimpiccertifeicate_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olimpic',
            name='certificate_generate',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Certificate Generate'),
        ),
        migrations.AlterField(
            model_name='olimpic',
            name='class_room',
            field=models.CharField(blank=True, choices=[('5-sinf', '5-sinf'), ('6-sinf', '6-sinf'), ('7-sinf', '7-sinf'), ('8-sinf', '8-sinf'), ('9-sinf', '9-sinf'), ('10-sinf', '10-sinf'), ('11-sinf', '11-sinf')], db_index=True, max_length=255, null=True, verbose_name='Class Room'),
        ),
        migrations.AlterField(
            model_name='olimpic',
            name='end_time',
            field=models.DateTimeField(db_index=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='olimpic',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='olimpic',
            name='is_all_users',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is All Users'),
        ),
        migrations.AlterField(
            model_name='olimpic',
            name='result_publish',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Result Publish'),
        ),
        migrations.AlterField(
            model_name='olimpic',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='is_answered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='is_correct',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='is_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userquestionoption',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
