# Generated by Django 4.2.11 on 2024-05-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimpic', '0024_alter_olimpic_certificate_generate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olimpic',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
