# Generated by Django 5.0.6 on 2024-05-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0025_olimpic_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestion",
            name="poll_id",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userquestion",
            name="user_olimpic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_questions",
                to="olimpic.userolimpic",
            ),
        ),
    ]
