# Generated by Django 5.0.6 on 2024-05-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("olimpic", "0027_userquestion_options_alter_userquestion_poll_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquestion",
            name="user_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_options",
                to="olimpic.option",
            ),
        ),
    ]
