# Generated by Django 4.2.11 on 2024-04-12 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('bot_token', models.CharField(max_length=255)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
                'db_table': 'telegram_bots',
            },
        ),
        migrations.CreateModel(
            name='TelegramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('telegram_id', models.PositiveBigIntegerField()),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone Number')),
                ('bith_day', models.DateField(blank=True, null=True, verbose_name='Bith Day')),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegrambot')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Telegram Profile',
                'verbose_name_plural': 'Telegram Profiles',
                'db_table': 'telegram_profiles',
            },
        ),
        migrations.CreateModel(
            name='RequiredGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('chat_id', models.CharField(help_text='Chat ID: -100000000 or Username: @username', max_length=255, verbose_name='Chat ID or Username')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegrambot')),
            ],
            options={
                'verbose_name': 'Required Group',
                'verbose_name_plural': 'Required Groups',
                'db_table': 'required_groups',
            },
        ),
    ]
