# Generated by Django 4.2.11 on 2024-04-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Button Name')),
                ('text', models.TextField(verbose_name='Button Text')),
                ('content', models.FileField(upload_to='buttons', verbose_name='Button Content')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegrambot', verbose_name='Telegram Bot')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegrambutton')),
            ],
            options={
                'verbose_name': 'Telegram Button',
                'verbose_name_plural': 'Telegram Buttons',
                'db_table': 'telegram_buttons',
            },
        ),
    ]
