# Generated by Django 4.2.11 on 2024-04-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegrambutton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambutton',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='buttons', verbose_name='Button Content'),
        ),
    ]
