# Generated by Django 4.2.11 on 2024-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegrambutton_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredgroup',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requiredgroup',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requiredgroup',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='telegrambutton',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='telegrambutton',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='telegrambutton',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='telegrambutton',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Button Name'),
        ),
        migrations.AddField(
            model_name='telegrambutton',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Button Name'),
        ),
        migrations.AddField(
            model_name='telegrambutton',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Button Name'),
        ),
    ]
