# Generated by Django 4.2.11 on 2024-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_alter_telegrambutton_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="_user_data",
            field=models.JSONField(
                blank=True, editable=False, null=True, verbose_name="User Data"
            ),
        ),
    ]
