# Generated by Django 4.2.11 on 2024-04-21 17:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_telegramprofile__user_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Notification Title"),
                ),
                (
                    "title_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Notification Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Notification Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Notification Title"
                    ),
                ),
                (
                    "text",
                    ckeditor.fields.RichTextField(verbose_name="Notification Text"),
                ),
                (
                    "text_uz",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Notification Text"
                    ),
                ),
                (
                    "text_ru",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Notification Text"
                    ),
                ),
                (
                    "text_en",
                    ckeditor.fields.RichTextField(
                        null=True, verbose_name="Notification Text"
                    ),
                ),
                (
                    "file_content",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="notifications",
                        verbose_name="Notification File Content",
                    ),
                ),
                (
                    "is_all_users",
                    models.BooleanField(default=False, verbose_name="Is All Users"),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bot.telegrambot",
                        verbose_name="Telegram Bot",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="bot.telegramprofile",
                        verbose_name="Users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
            },
        ),
    ]
