# Generated by Django 4.2.11 on 2024-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="is_olimpic",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
