# Generated by Django 4.2.11 on 2024-04-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_settings_bot_token"),
        ("bot", "0008_telegramprofile_is_olimpic"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.region",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.school",
                verbose_name="School",
            ),
        ),
    ]
