# Generated by Django 4.2.11 on 2024-04-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_settings_bot_token"),
        ("bot", "0009_telegramprofile_district_telegramprofile_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="region",
                to="common.region",
                verbose_name="Region",
            ),
        ),
    ]
