# Generated by Django 4.2.11 on 2024-04-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_telegramprofile_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramprofile',
            old_name='bith_day',
            new_name='birth_day',
        ),
    ]
