# Generated by Django 4.2.11 on 2024-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_rename_bith_day_telegramprofile_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='is_registered',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
