# Generated by Django 4.2.11 on 2024-04-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_telegramprofile_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], max_length=255, null=True),
        ),
    ]
