# Generated by Django 4.2.11 on 2024-04-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_district"),
        ("bot", "0013_alter_telegramprofile_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requiredgroup",
            options={
                "verbose_name": "Required Chats",
                "verbose_name_plural": "Required Chats",
            },
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.district",
                verbose_name="District",
            ),
        ),
    ]
