# Generated by Django 4.2.11 on 2024-04-28 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_district"),
        ("bot", "0014_alter_requiredgroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="class_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.class",
                verbose_name="Class",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_district",
                to="common.district",
                verbose_name="District",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_region",
                to="common.region",
                verbose_name="Region",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.school",
                verbose_name="School",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="users",
            field=models.ManyToManyField(
                blank=True, to="bot.telegramprofile", verbose_name="Users"
            ),
        ),
    ]
