# Generated by Django 4.2.11 on 2024-05-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_notification_class_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_not_registered',
            field=models.BooleanField(default=False, verbose_name='Is Not Registered'),
        ),
    ]
