# Generated by Django 5.0.6 on 2024-05-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0017_notification_is_not_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramprofile",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
    ]
